dziennik/dziennik/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('edziennik/', include('edziennik.urls')),
]

dziennik/edziennik/urls.py
from django.urls import path, include
from django.contrib.auth import views as auth_views
from .import views
from django.urls import  get_urlconf

urlpatterns = [
    path('', views.index, name='index'),
     path('accounts/', include('django.contrib.auth.urls')),
     path('logout/', auth_views.LogoutView.as_view() , name="logout"),
     path('abc',views.abc,name='abc'),
    # path('abcd', views.abcd, name='abcd'),
     path('szczegol/<int:idp>',views.szczegoly,name='szczegoly' ),
     path('edytuj/<int:idp>', views.edytuj, name='edytuj' ),
     path('zatwierdze/<int:idp>', views.zatwierdze, name='zatwierdze' ),
     path('dodajo/<int:idp>', views.dodajo, name='dodajo'),
     path('zatwierdzo/<int:idp>', views.zatwierdzo, name='zatwierdzo' ),
]

dziennik/edziennik/models.py
from django.db import models
from django.contrib.auth.models import User


class Osoba(models.Model):
    imie=models.CharField(max_length=15)
    nazwisko=models.CharField(max_length=30)
    pesel=models.CharField(max_length=9)
    user= models.ForeignKey(User, on_delete=models.CASCADE )
    class Meta:
        permissions=(("nauczyciel","nauczyciel v 2.0"),)




class Klasa(models.Model):
    klasa= models.CharField(max_length=3)

class Listaklasy(models.Model):
    id_k=models.ForeignKey(Klasa, on_delete=models.DO_NOTHING)
    id_u=models.ForeignKey(Osoba, on_delete=models.DO_NOTHING)

class Plan(models.Model) :
    id_k= models.ForeignKey(Klasa, on_delete=models.CASCADE)
    id_n= models.ForeignKey(Osoba, on_delete=models.CASCADE)
    przedmiot= models.CharField(max_length=30)


class Ocena(models.Model):
    id_u=models.ForeignKey(Osoba, on_delete=models.CASCADE)
    ocena = models.IntegerField()
    waga=models.IntegerField()
    id_n=models.ForeignKey(Plan, on_delete=models.DO_NOTHING)
    przedmiot= models.CharField(max_length=30)
    opis=models.CharField(max_length=100)

dziennik/edziennik/views.py
from django.shortcuts import render ,get_object_or_404 ,get_list_or_404
from django.http import HttpResponse
from django.shortcuts import render
from  django.utils.datastructures import MultiValueDictKeyError
from  django.contrib.auth.models import Group ,User
from  django.contrib.auth import authenticate ,get_user_model
from django.contrib.auth.forms import UserCreationForm
from .models import *
from django.views import generic
from django.views.generic.edit   import UpdateView
# funkcja zwracajacca grupe nr 0 brak lub bez log
# 1 uczen 2 nauczyciel
def check_grupa(request):
    nr_grupy = 0
    if request.user.is_authenticated:
        nr_grupy=1
        if request.user.has_perm('edziennik.nauczyciel'):
            nr_grupy=2
    return nr_grupy

def index(request) :
    return render(request,'index.html')

def login(request):
    return render(request,'index.html')

def abc(request):
    print("PRZED AUTORYZ  ")

    nr=check_grupa(request)
    if nr == 1:
        quest = get_object_or_404(Osoba, user_id=request.user.id)
        return render(request, 'glowna_u.html', {'quest': quest})
    elif nr == 2:
        quest = get_object_or_404(Osoba, user_id=request.user.id)
        quest2=get_list_or_404(Plan,id_n_id=quest.id)
        return render(request, 'glowna_n.html',{'quest': quest ,'quest2':quest2})
    else: return render(request, 'index.html')

def szczegoly(request,idp):

        nr=check_grupa(request)
        if nr==2:

            quest=get_object_or_404(Plan,id=idp)
            idk=quest.id_k_id

            idu=[]

            quest2=get_list_or_404(Listaklasy,id_k_id=idk)
            for i in range(len(quest2)):
                idu.append(quest2[i].id_u_id)
                print(quest2[i].id_u_id)
            quest3=get_list_or_404(Osoba, id__in=idu)
            return render(request,'szczegoly.html',{'quest2':quest2 , 'quest3':quest3 ,'idp':idp } )

        else: return render(request, 'index.html')

def edytuj(request,idp) :
    nr = check_grupa(request)
    if nr == 2:
        try:
            idu= request.POST['wybor']
        except MultiValueDictKeyError:
            quest = get_object_or_404(Plan, id=idp)
            idk = quest.id_k_id
            idu = []
            quest2 = get_list_or_404(Listaklasy, id_k_id=idk)
            for i in range(len(quest2)):
                idu.append(quest2[i].id_u_id)
            quest3 = get_list_or_404(Osoba, id__in=idu)
            return render(request, 'szczegoly.html', {'quest2': quest2, 'quest3': quest3, 'idp': idp})
        quest = get_object_or_404(Osoba, id=idu)
        quest2=get_list_or_404(Ocena,id_n_id=idp ,id_u_id=idu)
        return render(request,'edytuj.html',{'idp':idp ,'quest2':quest2 , 'quest':quest })
    else:
        return render(request, 'index.html')

def zatwierdze(request,idp):
        nr = check_grupa(request)
        if nr == 2:
            ido = request.POST['wybor']
            updatee=request.POST['new_ocena']
            if updatee=='0':
                Ocena.objects.filter(id=ido).delete()
            else :
                #zamien ocene
                Ocena.objects.filter(id=ido).update(ocena=updatee)
            quest = get_object_or_404(Osoba, user_id=request.user.id)
            quest2 = get_list_or_404(Plan, id_n_id=quest.id)
            return render(request, 'glowna_n.html', {'quest': quest, 'quest2': quest2})
        else:
                return render(request, 'index.html')






def dodajo(request,idp):
    nr = check_grupa(request)
    if nr == 2:
        quest=get_object_or_404(Plan, id=idp)
        quest2=get_list_or_404(Listaklasy,id_k_id=quest.id_k_id)
        idu=[]
        for i in range(len(quest2)):
            idu.append(quest2[i].id_u_id)
            print(quest2[i].id_u_id)
        quest3=get_list_or_404(Osoba,id__in=idu)
        return render(request,'dodajo.html',{'idp':idp ,'quest2':quest2 , 'quest':quest ,'quest3':quest3 })
    else:
        return render(request, 'index.html')

def zatwierdzo(request,idp):
    nr = check_grupa(request)
    if nr == 2:
        ile =0
        ile=int (request.POST['ile'])
        quest=get_object_or_404(Plan,id=idp)
        for n in range(ile):
            numer=str(n+1)
            ocenai ='new_ocena'+numer

            ocena = request.POST[ocenai]
            if ocena!='0':
                waga=request.POST['waga']
                opis=request.POST['opis']
                idui = 'idu' + numer
                idu = request.POST[idui]
                statment=Ocena(id_u_id=idu ,ocena=ocena,waga=waga , przedmiot=quest.przedmiot ,id_n_id=idp,opis=opis )
                statment.save()

        quest = get_object_or_404(Osoba, user_id=request.user.id)
        quest2 = get_list_or_404(Plan, id_n_id=quest.id)
        return render(request, 'glowna_n.html', {'quest': quest, 'quest2': quest2})
    else:
        return render(request, 'index.html')

dziennik/edziennik/templates/abc.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
zalogowano {{user.username}} <br>
id=   {{user.id}} <br>

<a href="{% url 'abcd' %}">2 strona</a>
</body>
</html>

dziennik/edziennik/templates/abcd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> to jest 2 strona</h1>  <br>

zalogowano {{user.username}} <br>
id=   {{user.id}} <br>
group= {{user.groups}}
</body>
</html>

dziennik/edziennik/templates/dodajo.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<form action="{% url 'zatwierdzo' idp  %}" method="post">
{% csrf_token %}
{% for listaa in quest2 %}
{% for osoba in quest3%}
{%if osoba.id == listaa.id_u_id %}
{{osoba.nazwisko}} {{osoba.imie}}

<select name="new_ocena{{ forloop.counter }}" id="new_ocena{{ forloop.counter }}">
    <option value="0">brak</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
</select>
<input type="hidden" name="idu{{ forloop.counter }}" id="idu{{ forloop.counter }}" value="{{osoba.id}}">

{% endif %}
    <input type="hidden" name="ile" id="ile" value="{{forloop.counter}}">
{%endfor%}
<br>


{%endfor%}
    <br>
waga <input type="number" name="waga"> <br>
  opis  <input type="text" name="opis">
  <input type="submit" value="dodaj">
</form>




</body>
</html>

dziennik/edziennik/templates/edytuj.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

edytuj oceny ucznia: {{quest.imie}} {{quest.nazwisko}}

<form action="{% url 'zatwierdze' idp  %}" method="post">
{% csrf_token %}
{% for ocena in quest2 %}
    <input type="radio" name="wybor" id="wybor{{ ocena.id }}" value="{{ ocena.id }}">
<a href="#" data-toggle="tootip" title="{{ocena.opis}}  waga: {{ocena.waga}} "> {{ocena.ocena}}</a>

<br>
{%endfor%}
<select name="new_ocena" id="new_ocena">
    <option value="0">usun</option>
    <option value="1">1</option>
    <option value="2">2</option>
    <option value="3">3</option>
    <option value="4">4</option>
    <option value="5">5</option>
    <option value="6">6</option>
</select>
    <input type="submit" value="zatwierdz">
</form>


</body>
</html>

dziennik/edziennik/templates/glowna_n.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1> Witaj nauczycicelu  {{quest.imie}}  {{quest.nazwisko}}<h1> <br>
<br>


{% for plan in quest.plan_set.all %}
<li>
    {{plan.przedmiot}}
<a href="{% url 'szczegoly' plan.id%}"> szczegoly </a>
</li>

{%endfor%}

</body>
</html>

dziennik/edziennik/templates/glowna_u.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>Witaj uczniu
{{quest.imie}}  {{quest.nazwisko}}</h1> <br>

{% for ocena in quest.ocena_set.all|dictsort:"przedmiot" %}
{% ifchanged ocena.przedmiot %}<br>
        <h2>{{ocena.przedmiot}} : </h2>
 {%endifchanged%}

<a href="#" data-toggle="tootip" title="{{ocena.opis}}  waga: {{ocena.waga}} "> {{ocena.ocena}}</a>
{%endfor%}


</body>
</html>

dziennik/edziennik/templates/index.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

<body>
<h1> Witaj w e-dzienniku</h1> <br>
<a href="{% url 'login' %}">logowanie</a> <br>
<a href="{% url 'logout' %}">wyloguj</a>
</body>
</html>

dziennik/edziennik/templates/szczegoly.html
{%load static%}
<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="{% url 'edytuj' idp  %}" method="post">
{% csrf_token %}
{% for osoba in quest3 %}
    <input type="radio" name="wybor" id="wybor{{ osoba.id }}" value="{{ osoba.id }}">
{% csrf_token %}
{{osoba.imie}} {{osoba.nazwisko}}

{% for ocena in osoba.ocena_set.all %}
{% if ocena.id_n_id == idp %}

<a href="#" data-toggle="tootip" title="{{ocena.opis}}  waga: {{ocena.waga}} "> {{ocena.ocena}}</a>
{%endif%}
{%endfor%}

<br>
{%endfor%}

<input type="submit" value="edytuj">
</form>
<form action="{% url 'dodajo' idp  %}" method="get">
  <input type="submit" value="dodaj ocene">

</form>



</body>
</html>